apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      env:
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: snyk-token
              key: token
      - name: snyk-cli
        image: snyk/snyk-cli:npm
        command: ["/bin/sh","-c"]
        args:
          - git clone https://github.com/jiajunngjj/argocd-example-apps.git
          - snyk auth $SNYK_TOKEN
          - snyk iac test guestbook/guestbook-ui-deployment.yaml
      restartPolicy: Never
  backoffLimit: 0
